### ISSUE TITLE
Get working on Windows

### ISSUE THREAD

**Issue by agundy** [rcos/observatory-server#135]
Document how to get it running on windows too.

**Comment by seveibar** [comment]
@digitalninja status update?

**Comment by digitalninja** [comment]
@seveibar: Sorry.. I just saw the message on github. I'm stuck with the VM... It's refusing to serve up grunt as it can't seem to find the gruntfile. No idea why thats happening though even after firing the command from the directory which has the gruntfile.

**Comment by vkr96** [comment]
So then this is just documenation right? I should just like upload a README for doing windows?

**Comment by kmcnellis** [comment]
Unless someone get vagrant working, yes. Basically documentation on how to get up and running

**Comment by kmcnellis** [comment]
@vkr96 Status on this?

**Comment by aeksco** [comment]
I'm going to close this - the README.md currently assumes that Docker and NPM are installed on the user's system - at this point there is virtually no platform-specific configuration that needs to take place.
