### ISSUE TITLE
User profile page should never return password field to client

### ISSUE THREAD

**Issue by agundy** [rcos/observatory-server#209]
This is a test of the get user api endpoint, your test should validate that the users password is never given out. It currently is not but we need to keep it that way.

**Comment by helei96** [comment]
chris n helen on this

**Comment by agundy** [comment]
this will look like '/server/api/project/project.spec.js' but in '/server/api/user/user.spec.js a brand new file. people in #205 are doing similar things and may be able to work with them.

**Comment by zmike808** [comment]
This is a pretty old issue. Has this been fixed already? https://github.com/rcos/Observatory3/issues/205 has been closed, and Aaron said that issue was related so I'm assuming that this has been fixed?

**Comment by aeksco** [comment]
This appears to have been resolved - don't see password fields included anywhere in our user-centric queries.
