### ISSUE TITLE
Achievements Page Design Comment

### ISSUE THREAD

**Issue by agundy** [rcos/observatory-server#496]
"This looks good but (visually) looks iffy on the home page. Perhaps the "Achievements" hotlink should be moved to the menu bar instead of existing in a separate space?"

**Comment by agundy** [comment]
For the record i agree that this could be improved. Initial PR just addressed linking to the page. Reason I didn't link to it from top bar is it felt like it would take up a ton of space and is a little less core to the product. not logged in the top bar is fine but mentors are starting to get a crowded top bar

**Comment by TheoBr** [comment]
I would be okay with all mentor functions being condensed to a drop-down, the achievements of RCOS are important enough to hold a spot in the top bar

**Comment by aeksco** [comment]
Marking this as a `wontfix` and closing - Achievements are being migrated to `blog.rcos.io` and the page will be pulled out of Observatory completely
