### ISSUE TITLE
Comments on Blog Posts

### ISSUE THREAD

**Issue by AdrianCollado** [rcos/observatory-server#505]
I think it would be interesting to have comments on blog posts, as there are times when I wish I could respond to a blog entry, but cannot.

**Comment by vkr96** [comment]
This is a good idea, will try and implement

**Comment by aeksco** [comment]
This isn't something we're going to implement - I'm marking this as `out of scope`. 

Observatory is _not_ a blogging platform - if we want more features from blogs (comments, drafts, published state, RSS) we should start to investigate turn-key platforms that facilitate those use cases - closing.
