### ISSUE TITLE
Add more info to the RCOS Main Page

### ISSUE THREAD

**Issue by Phansa** [rcos/observatory-server#640]
I think the RCOS Main page can go over the history of RCOS and note some significant student projects (YACS/Submitty). Additionally, it could cover more of the process behind RCOS - how the first weeks you can find a project to work on then submit an Undergraduate Research Proposal(and link to this form) to do it for credit or do it for experience under the details tab. I think it should be easy for people who are interested in RCOS to get a better sense of what it is about and how to join.  Potential text to add is -  "Anyone can show up to the friday meetings and listen to the tech talks/project presentations given. If you want to work on an existing project you can talk to the people working on it or if you want to start your own project you can make pitch slides and work on that. Projects can cover fields such as Machine Learning, Web Development, Software Engineering, Hardware etc..  as long as they meet the criteria of being open source. Additionally, you can contribute to any existing open source project."

**Comment by aeksco** [comment]
I'm going to mark this as closed - the rework of Observatory's front-end code (in [observatory-client](https://github.com/rcos/observatory-client/)) is already tackling this issue.
