### ISSUE TITLE
Save current blog edit locally for recovery purposes

### ISSUE THREAD

**Issue by connection-lost** [rcos/observatory-server#658]
My friend just lost his blog post right in front of me due to a browser crash.

I think it would be a good idea to save the blog edit locally every x minutes as a cookie. Browser will load the unpublished blog post once user open the blog edit page. This won't be a difficult implementation.

Ideas?

**Comment by aeksco** [comment]
After some discussion we've elected to remove blogging features from Observatory - in light of that development this feature have been marked as `wontfix` and I'll be closing this issue :)
